version: '3.8'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./services/django/.env.dev
      - ./services/postgresql/.env
  postgresql:
    image: postgres:13.4-alpine
    hostname: $${POSTGRES_HOST}
    container_name: halo-db
    env_file:
      - services/postgresql/.env
    ports:
      - "5920:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: