version: '3.8'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./services/django/.env.dev
      - ./services/postgresql/.env
    depends_on:
      - redis
  postgresql:
    image: postgres:13.4-alpine
    hostname: $${POSTGRES_HOST}
    container_name: postgresql
    env_file:
      - services/postgresql/.env
    ports:
      - "5920:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - services/django/.env.dev
      - services/celery/.env
      - services/postgresql/.env
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A core beat -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - services/django/.env.dev
      - services/celery/.env
      - services/postgresql/.env
    depends_on:
      - redis

volumes:
  postgres_data: