# Generated by Django 4.0.4 on 2022-05-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_photo_is_avatar_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodings',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_groups', to='analyze.group'),
        ),
        migrations.AlterField(
            model_name='encodings',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_photos', to='analyze.photo'),
        ),
    ]
